language: bash
services: docker

branches:
  only:
    - feature/travis-build

script:
  - cd source
  - docker build . -t "sheepit/sheepit:travis" -t "sheepit/sheepit:travis-build-$TRAVIS_BUILD_NUMBER"
  - echo "$dockerhubpassword" | docker login --username "$dockerhublogin" --password-stdin
  - docker push sheepit/sheepit:travis

after_script:
  - docker images