language: bash
services: docker

branches:
  only:
    - feature/travis-build

script:
  - cd source
  - docker build . -t sheepit/sheepit:travis
  - echo "$dockerhubpassword" | docker login --username "$dockerhublogin" --password-stdin
  - docker push sheepit/sheepit:travis

after_script:
  - docker images