version: '3.1'

services:

  sheepit:
    image: sheepit/sheepit:latest
    build: ../source/
    restart: always
    ports:
      - 8080:80
      - 443:443
    environment:
      ASPNETCORE_ENVIRONMENT: development
      BASE_URL: https://localhost:443/
      ASPNETCORE_URLS: "https://+443;http://+80"
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ConnectionStrings:SheepItContext: Host=postgres;Database=sheepit;Username=postgres;Password=postgres
    networks:
      - sheepit-network
    volumes:
      - sheepit-volume:/data
      - ${HOME}/.aspnet/https:/https/

  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - sheepit-network
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - 8082:80
    depends_on:
      - postgres
    networks:
      - sheepit-network

volumes:
  sheepit-volume:
  postgres-volume:

networks:
  sheepit-network:
    driver: bridge