version: '3.1'

services:

  sheepit:
    image: sheepit/sheepit:latest
    build: ../source/
    restart: always
    ports:
      - 8080:80
      - 443:443
    environment:
      ASPNETCORE_ENVIRONMENT: development
      BASE_URL: https://localhost:443/
      Mongo:ConnectionString: mongodb://root:example@mongo:27017
      ASPNETCORE_URLS: "https://+443;http://+80"
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - sheepit-volume:/data
      - ${HOME}/.aspnet/https:/https/

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-volume:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:      
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
    sheepit-volume:
    mongo-volume: